package sintactico;

import backend.BackTables;
import c3a.GeneratorC3A;
import c3a.InstructionC3A.Code;
import errores.CompilerError;
import errores.SymTabError;
import generatorAssembler.GeneratorAssembler;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import lexico.Lexico;
import core.*;
import symbolsTable.SymbolsTable;
import symbolsTable.Type;
import symbolsTable.Type.Tipo;
import symbolsTable.Type.TipoSubyacente;

import java.util.ArrayList;
import java.util.List;
import java.util.Stack;

class Parser;

parser code
{:
  private SymbolsTable symbolsTable;
  private BackTables backTables;
  private Lexico lexico;
  private GeneratorC3A c3a_g;
  private GeneratorAssembler assembler;
  private String filename;

  private Stack<String> labelTrueStack;
  private Stack<String> labelFalseStack;

  public Parser(Lexico lexico, ComplexSymbolFactory sf){
    super(lexico, sf);
    this.lexico = lexico;
    this.symbolsTable = new SymbolsTable();
    this.backTables = new BackTables(symbolsTable);
    this.c3a_g = new GeneratorC3A();
    this.assembler = new GeneratorAssembler(symbolsTable, backTables, c3a_g, "Example");
    this.labelTrueStack = new Stack<String>();
    this.labelFalseStack = new Stack<String>();
  }
  public Parser(Lexico lexico, ComplexSymbolFactory sf, String filename){
      super(lexico, sf);
      this.lexico = lexico;
      this.filename = filename;
      this.symbolsTable = new SymbolsTable(filename);
      this.backTables = new BackTables(symbolsTable, filename);
      this.c3a_g = new GeneratorC3A(filename);
      this.assembler = new GeneratorAssembler(symbolsTable, backTables, c3a_g, filename);
      this.labelTrueStack = new Stack<String>();
      this.labelFalseStack = new Stack<String>();

    }

  private void closeErrorFiles(){
    SymTabError.closeFile();
    CompilerError.closeFiles();
  }

  public void syntax_error(Symbol s) {
    try {
      ArrayList<Integer> expected = new ArrayList<Integer>(expected_token_ids());
      ArrayList<String> expected_names = new ArrayList<String>();

      for(Integer i : expected){
        expected_names.add(symbl_name_from_id(i));
      }

      ComplexSymbol complexSymbol = (ComplexSymbol) s; 

      throw new CompilerError(complexSymbol, expected_names, true);
    } catch (Exception e) {
		};
  }

  public void unrecovered_syntax_error(Symbol s){
    try {
      ArrayList<Integer> expected = new ArrayList<Integer>(expected_token_ids());
      ArrayList<String> expected_names = new ArrayList<String>();

      for(Integer i : expected){
        expected_names.add(symbl_name_from_id(i));
      }

      lexico.closeFile((s.left+1), (s.right+1));

      ComplexSymbol complexSymbol = (ComplexSymbol) s; 

      throw new CompilerError(complexSymbol, expected_names, false);
    } catch (Exception e) {
      closeErrorFiles();
		};
  }

  private void initTypes() {
    try{
      //init TUPLE type
      Type tuple_type = new Type(Tipo.dtype, TipoSubyacente.TS_TUPLE, 0);
      symbolsTable.add("tuple", tuple_type);

      //init NUMBER type
      Type number_type = new Type(Tipo.dtype, TipoSubyacente.TS_NUMBER, 16);
      symbolsTable.add("number", number_type);

      // init String type
      Type str_type = new Type(Tipo.dtype, TipoSubyacente.TS_STRING, 16);
      symbolsTable.add("string", str_type);

      //init BOOLEAN type
      Type bool_type = new Type(Tipo.dtype,TipoSubyacente.TS_BOOLEAN, 16);
      symbolsTable.add("boolean",bool_type);

      //init VOID type
      Type void_type = new Type(Tipo.dtype, TipoSubyacente.TS_NULL, 0);
      symbolsTable.add("void", void_type);
    }catch (SymTabError e){
      closeErrorFiles();
    }
  }

:};

// Terminal Symbols

terminal String id, number, string, bool, struct, op_relational, op_logical, op_logical_not, op_arithmetical_c, op_arithmetical_b;

terminal        op_assig, IF, ELIF, ELSE,
                WHILE, FUNC, RETURN, constant, FOR,
                READ, PRINT, lparen, rparen, lbrace, rbrace, lbracket, rbracket,
                semicolon, comma, two_points, dot, MAIN;


// Non-terminal Symbols

non terminal  Start                STARTS;
non terminal  Init                  INIT;

non terminal  MainLabel                 M_MAIN;
non terminal  MainS                  MAIN_S;
non terminal  MainInstructions             MAIN_INSTRUCTIONS;

non terminal  Instructions          INSTRUCTIONS;
non terminal  Instruction           INSTRUCTION;

non terminal  BlockIn               BLOCK_IN;
non terminal  BlockOut              BLOCK_OUT;

non terminal  Declarations          DECLARATIONS, DECLARATION;

non terminal  Const              CONSTANT;

non terminal  NumericValue             NUMBER_VALUE;
non terminal  Identifier                 ID_VALUE;
non terminal  StringValue             STRING_VALUE;
non terminal  BooleanValue               BOOLEAN_VALUE;

non terminal  Value                 VALUE;

non terminal  Assignation   OPERATOR_ASSIG;
non terminal  InstructionOut        INSTRUCTION_OUT;

non terminal  ArithmeticOperator         ARITH_OP;
non terminal  ArithmeticOperation        ARITHMETICAL_OPERATION;
non terminal  ArithmeticValue            ARITHMETICAL_VALUE;

non terminal  BooleanOperator                BOOLEAN_OPERATION;
non terminal  BooleanOperationValue           BOOLEAN_OP_VALUE;
non terminal  ValuesComparison       VALUE_COMPARISON;
non terminal  End                  M_END;
non terminal  Condition             COND;
non terminal  CondFalse        COND_F;
non terminal  CondTrue         COND_T;
non terminal  InstructionIf         INSTRUCTION_IF;
non terminal  ElseIf                  INSTRUCT_ELIF;
non terminal  Else                  INSTRUCT_ELSE;
non terminal  WhileLabel                M_WHILE;
non terminal  ForBody               FOR_BODY;
non terminal  ForLabel              LABEL_FOR;
non terminal  LabelPostFor          LABEL_POST_FOR;
non terminal  InstructionWhile      INSTRUCTION_WHILE;
non terminal  InstructionFor        INSTRUCTION_FOR;
non terminal  DeclareFunctions      DECLARE_FUNCTIONS;
non terminal  DefineFunction           DEFINE_FUNCTION;
non terminal  FunctionInit               FUNCTION_INIT;
non terminal  FunctionParams             FUNCTION_PARAMS;
non terminal  FunctionWithParams            FUNCTION_W_PARAMS;
non terminal  FunctionInstructions       FUNCTION_INSTRUCTIONS;
non terminal  FunctionReturn             FUNCTION_RETURN;

non terminal  CallFunction          CALL_FUNCTION;
non terminal  CallBody              CALL_BODY;

non terminal                        TUPLE_ACCESS;
non terminal    TupleDeclaration    TUPLE_DECLARATION;
non terminal    FieldList           FIELD_LIST;
non terminal    TupleField          TUPLE_FIELD;
non terminal    TupleValues         TUPLE_VALUE;
non terminal    TupleValues         TUPLE_VALUES;

non terminal  Empty                 EMPTY;

// precedences
precedence left op_arithmetical_b;
precedence left op_arithmetical_c;
precedence left op_logical;
precedence left op_logical_not;

start with STARTS;

STARTS                      ::=  INIT DECLARE_FUNCTIONS
                            {:
                            // close SymbolsTableData.txt file
                              symbolsTable.closeSymbolsTableFiles();
                              backTables.guardarTablasBack();

                              c3a_g.guardarC3Dir();
                              assembler.generateAssembler();

                              closeErrorFiles();
                            :};

INIT                        ::= {:
                              initTypes();
                              RESULT = new Init();
                            :};

DECLARE_FUNCTIONS           ::= DEFINE_FUNCTION DECLARE_FUNCTIONS
                            {:
                              RESULT = new DeclareFunctions();
                            :}
                            | MAIN_S
                            {:
                              RESULT = new DeclareFunctions();
                            :};

MAIN_S                        ::= FUNC MAIN M_MAIN lparen rparen lbrace BLOCK_IN MAIN_INSTRUCTIONS BLOCK_OUT rbrace {:
                              c3a_g.generateC3aInstr(
                                Code.rtn,
                                null,
                                null,
                                "PROC_main"
                              );

                              RESULT = new MainS();
                            :};

M_MAIN                      ::=
                            {:

                              String backId = backTables.addMain();
                              Type fun_type = new Type(backId, Tipo.dfun, null);
                              symbolsTable.add("main", fun_type);

                              c3a_g.generateC3aInstr(
                                Code.skip,
                                null,
                                null,
                                "main"
                              );

                              c3a_g.generateC3aInstr(
                                Code.pmb,
                                null,
                                null,
                                backId
                              );

                              RESULT = new MainLabel();
                            :};

MAIN_INSTRUCTIONS           ::= INSTRUCTIONS
                            {:
                              RESULT = new MainInstructions();
                            :}
                            | EMPTY
                            {:
                              RESULT = new MainInstructions();
                            :};

INSTRUCTIONS                ::= INSTRUCTIONS INSTRUCTION
                            {:
                              RESULT = new Instructions();
                            :}
                            | INSTRUCTION
                            {:
                              RESULT = new Instructions();
                            :};

INSTRUCTION                 ::=  DECLARATIONS semicolon
                            {:
                              RESULT = new Instruction();
                            :}
                            | TUPLE_DECLARATION semicolon
                            {:
                              RESULT = new Instruction();
                            :}
                            | INSTRUCTION_IF
                            {:
                              RESULT = new Instruction();
                            :}
                            | INSTRUCTION_WHILE
                            {:
                              RESULT = new Instruction();
                            :}
                            | INSTRUCTION_FOR
                            {:
                              RESULT = new Instruction();
                            :}
                            | OPERATOR_ASSIG semicolon
                            {:
                              RESULT = new Instruction();
                            :}
                            | INSTRUCTION_OUT semicolon
                            {:
                              RESULT = new Instruction();
                            :}
                            | CALL_FUNCTION semicolon
                            {:
                              RESULT = new Instruction();
                            :};

BLOCK_IN                    ::=
                            {:
                              symbolsTable.enterBlock();
                              RESULT = new BlockIn();
                            :};

BLOCK_OUT                   ::=
                            {:
                              try{
                                symbolsTable.leaveBlock();
                                RESULT = new BlockOut();
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :};

DECLARATIONS                ::=  id:var_id comma DECLARATIONS:declarations
                            {:
                              try{
                                Type type = declarations.getType();
                                String backId;

                                if(type.getTipoSubyacente() == TipoSubyacente.TS_STRING){
                                  String value = declarations.getValue();
                                  backId = backTables.addStringVariable(var_id, type.getSize(), value);
                                }else{
                                  backId = backTables.addVariable(var_id, type.getTipoSubyacente(), type.getSize(), false);
                                }

                                type.setIdBack(backId);

                                symbolsTable.add(var_id, type);

                                c3a_g.generateC3aInstr(
                                  Code.copy,
                                  declarations.getVarId(),
                                  null,
                                  backId
                                );

                                  RESULT = declarations;

                              }catch(SymTabError e){
                                String from = var_idxleft.getLine() + ":" + var_idxleft.getColumn();
                                String to = var_idxright.getLine() + ":" + var_idxright.getColumn();
                                String message = e.getMessage() + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | DECLARATION:declaration
                            {:
                              RESULT = declaration;
                            :}
                            ;

TUPLE_DECLARATION           ::= struct lbrace FIELD_LIST:field_list rbrace id:var_id
                            {:
                            Type type = symbolsTable.get("tuple");
                            type.setSize(field_list.getSize());
                            type.setTiposSubyacentes(field_list.getTiposSubyacentes());
                            symbolsTable.add(var_id, type);
                            RESULT = new TupleDeclaration(var_id, field_list, field_list.getSize());
                            :}
                            ;

FIELD_LIST                  ::= FIELD_LIST:field_list semicolon TUPLE_FIELD:field
                            {:
                            field_list.addField(field);
                            RESULT = field_list;
                            :}
                            | TUPLE_FIELD:field
                            {:
                            ArrayList<TupleField> tupleFields = new ArrayList<>();
                            tupleFields.add(field);
                            RESULT = new FieldList(tupleFields);
                            :}
                            ;

TUPLE_FIELD                 ::= id:id_var two_points id:type_id
                            {:
                            Type type = symbolsTable.get(type_id);
                            if(type == null || type.getTipo() != Tipo.dtype){
                              String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                              String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                              String message = "Invalid type" + " from "+from+" to "+to;
                              throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                            }

                            String backId;
                            backId = backTables.addVariable(id_var, type.getTipoSubyacente(), type.getSize(), false);
                            type.setIdBack(backId);

                            RESULT = new TupleField(id_var, type);
                            :}
                            ;

DECLARATION                 ::=  id:id_var CONSTANT:constant two_points id:type_id op_assig VALUE:value
                            {:
                              try {

                                boolean isConst = constant != null ? constant.getIsConst() : false;

                                Type type = symbolsTable.get(type_id);

                                if(type == null || type.getTipo() != Tipo.dtype){
                                  String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                  String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                  String message = "Invalid type" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                if(type.getTipoSubyacente() != TipoSubyacente.TS_BOOLEAN
                                  && type.getTipoSubyacente() != TipoSubyacente.TS_NUMBER
                                  && type.getTipoSubyacente() != TipoSubyacente.TS_STRING){
                                    String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                    String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                    String message = "DECLARATION: Invalid subjacent type" + " from "+from+" to "+to;
                                    throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                //IF LITERALL (type = null) CHECK SUBJACENT Tipo
                                if(value.getTipo() == Tipo.dnull && type.getTipoSubyacente() != value.getTipoSubyacente()){
                                  String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                  String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                  String message = "Value and type must have same subjacent type" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                if(value.getTipo() != Tipo.dnull && !value.getTypeName().equals(type_id)){
                                  String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                  String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                  String message = "Value and type must have same subjacent type" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                Type var_type;

                                if(isConst){
                                  var_type = new Type(Tipo.dconst, type_id, value.getValue());
                                }
                                else{
                                  var_type = new Type(Tipo.dvar, type_id);
                                }

                                int size = type.getSize();
                                if(value.getIsString()){
                                  size = value.getStringSize();
                                }

                                String var_id;
                                if(type.getTipoSubyacente() == TipoSubyacente.TS_STRING){
                                  String str_value = (String) value.getValue();
                                  var_id = backTables.addStringVariable(id_var, type.getSize(), str_value);
                                }else{
                                  var_id = backTables.addVariable(id_var, type.getTipoSubyacente(), type.getSize(), false);
                                }

                                var_type.setIdBack(var_id);

                                String val_id = value.getVarId();
                                symbolsTable.add(id_var, var_type);

                                Declarations symDcls;
                                if(value.getIsString()){
                                  symDcls = new Declarations(val_id, var_type, (String) value.getValue());
                                }else{
                                  symDcls = new Declarations(val_id, var_type);
                                }

                                if(type.getTipoSubyacente() != TipoSubyacente.TS_STRING){
                                  c3a_g.generateC3aInstr(
                                    Code.copy,
                                    val_id,
                                    null,
                                    var_id
                                  );
                                }

                                RESULT = symDcls;
                              }catch(SymTabError e){
                                String from = id_varxleft.getLine() + ":" + id_varxleft.getColumn();
                                String to = id_varxright.getLine() + ":" + id_varxright.getColumn();
                                String message = e.getMessage() + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | id:id_var CONSTANT two_points id:type_id op_assig TUPLE_VALUE:tuple_value
                            {:
                            Type type = symbolsTable.get(type_id);

                            if(type == null || type.getTipo() != Tipo.dtype){
                              String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                              String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                              String message = "Invalid type" + " from "+from+" to "+to;
                              throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                            }

                            if(type.getTipoSubyacente() != TipoSubyacente.TS_TUPLE){
                                String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                String message = "DECLARATION: Invalid subjacent type" + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                            }

                            //COMPROBAMOS QUE LA CANTIDAD DE VALORES COINCIDA CON LA CANTIDAD DE VARIABLES DE LA TUPLA
                            if(type.getTiposSubyacentes().size() != tuple_value.getValues().size()){
                                String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                String message = "TUPLE_DECLARATION: Invalid number of values" + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                            }

                            //COMPROBAMOS QUE LOS TIPOS DE LOS VALUES SEAN COMPATIBLES CON LOS TIPOS DE LA TUPLA
                            for (int i = 0; i < tuple_value.getValues().size(); i++){
                                if(type.getTiposSubyacentes().get(i) != tuple_value.getValues().get(i).getTipoSubyacente()){
                                    String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                    String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                    String message = "TUPLE_DECLARATION: Invalid subjacentType of value" + " from "+from+" to "+to;
                                    throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }
                            }

                            :}
                            ;

TUPLE_ACCESS                ::= id:tuple dot id:attribute
                            {:
                            System.out.println("Identificador: " + tuple + " | Atributo: " + attribute);
                            :}
                            ;

CONSTANT                    ::=  constant
                            {:
                              RESULT = new Const(true);
                            :}
                            |  EMPTY
                            {:
                              RESULT = new Const(false);
                            :};

OPERATOR_ASSIG              ::= id:var_id op_assig VALUE:value
                            {:
                              try {
                                   Type varType = symbolsTable.get(var_id);
                                   String type_id = varType.getTypeName();

                                   if (varType.getTipo() == Tipo.dconst) {
                                       String from = var_idxleft.getLine() + ":" + var_idxleft.getColumn();
                                       String to = valuexright.getLine() + ":" + valuexright.getColumn();
                                       String message = "Cant assign value to constant" + " from " + from + " to " + to;
                                       throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                   }

                                   //IF LITERALL (type = null) CHECK SUBJACENT Tipo
                                   if (value.getTipo() == Tipo.dnull && varType.getTipoSubyacente() == value.getTipoSubyacente()) {
                                       String from = var_idxleft.getLine() + ":" + var_idxleft.getColumn();
                                       String to = valuexright.getLine() + ":" + valuexright.getColumn();
                                       String message = "Value and type must have same subjacent type" + " from " + from + " to " + to;
                                       throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                   }

                                   if (value.getTipo() != Tipo.dnull && !value.getTypeName().equals(type_id)) {
                                       String from = var_idxleft.getLine() + ":" + var_idxleft.getColumn();
                                       String to = valuexright.getLine() + ":" + valuexright.getColumn();
                                       String message = "ValueType and type_id must be the same type" + " from " + from + " to " + to;
                                       throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                   }

                                   c3a_g.generateC3aInstr(
                                           Code.copy,
                                           value.getVarId(),
                                           null,
                                           varType.getBackendId()
                                   );

                                   RESULT = new Assignation();
                              } catch (SymTabError e) {
                                  String from = var_idxleft.getLine() + ":" + var_idxleft.getColumn();
                                  String to = var_idxright.getLine() + ":" + var_idxright.getColumn();
                                  String message = e.getMessage() + " from " + from + " to " + to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }
                            :};

ARITH_OP                    ::= op_arithmetical_b:op
                            {: RESULT = new ArithmeticOperator(op); :}
                            | op_arithmetical_c:op
                            {: RESULT = new ArithmeticOperator(op); :};

ARITHMETICAL_OPERATION      ::= ARITHMETICAL_VALUE:arith_val1 ARITH_OP:op ARITHMETICAL_VALUE:arith_val2
                            {:
                              try{
                                ArithmeticOperation sym;
                                boolean allConst = arith_val1.getIsConst() && arith_val2.getIsConst();

                                Code op_code;

                                switch(op.getOperator()){
                                  case "+" :
                                    op_code = Code.add;
                                    break;
                                  case "-" :
                                    op_code = Code.sub;
                                    break;
                                  case "*" :
                                    op_code = Code.prod;
                                    break;
                                  case "/" :
                                    op_code = Code.div;
                                    break;
                                  case "%" :
                                    op_code = Code.mod;
                                    break;
                                  default :
                                    String from = opxleft.getLine() + ":" + opxleft.getColumn();
                                    String to = opxright.getLine() + ":" + opxright.getColumn();
                                    String message = "Invalid arithmetic operator from "+from+" to "+to;
                                    throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                Integer value = null;
                                if(allConst) {
                                  Integer val1 = (Integer) arith_val1.getValue();
                                  Integer val2 = (Integer) arith_val2.getValue();

                                  switch(op.getOperator()){
                                    case "+" :
                                      value = val1 + val2;
                                      break;
                                    case "-" :
                                      value = val1 - val2;
                                      break;
                                    case "*" :
                                      value = val1 * val2;
                                      break;
                                    case "/" :
                                      if(val2 == 0){
                                        String from = arith_val2xleft.getLine() + ":" + arith_val2xleft.getColumn();
                                        String to = arith_val2xright.getLine() + ":" + arith_val2xright.getColumn();
                                        String message = "Can not divide by zero (0)" + " from "+from+" to "+to;
                                        throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                      }
                                      value = val1 / val2;
                                      break;
                                    case "%" :
                                      value = val1 % val2;
                                      break;
                                  }
                                }

                                Type type_number = symbolsTable.get("number");

                                String var_id = backTables.addTempVar(type_number.getSize(), type_number.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  op_code,
                                  arith_val1.getVarId(),
                                  arith_val2.getVarId(),
                                  var_id
                                );

                                if(allConst){
                                  sym = new ArithmeticOperation(var_id, value);
                                }
                                else{
                                  sym = new ArithmeticOperation(var_id);
                                }

                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | op_arithmetical_b:op lparen ARITHMETICAL_OPERATION:arith_op rparen
                            {:
                              try{
                                ArithmeticOperation sym = arith_op;
                                if(op.equals("-")){
                                  Type type_number = symbolsTable.get("number");
                                  String var_id = backTables.addTempVar(type_number.getSize(),  type_number.getTipoSubyacente());

                                  if(arith_op.getIsConst()){
                                    Integer value = - arith_op.getValue().intValue();
                                    sym = new ArithmeticOperation(arith_op.getVarId(), value);
                                  }else{
                                    sym = new ArithmeticOperation(var_id);
                                  }

                                  c3a_g.generateC3aInstr(
                                    Code.neg,
                                    arith_op.getVarId(),
                                    null,
                                    var_id
                                  );
                                }

                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | lparen ARITHMETICAL_OPERATION:arith_op rparen
                            {:
                              RESULT = arith_op;
                            :};

NUMBER_VALUE                ::= number:n_val
                            {:
                              Integer value = Integer.valueOf(n_val);
                              RESULT = new NumericValue(value);
                            :}
                            | lparen NUMBER_VALUE:n_val rparen
                            {:
                              RESULT = n_val;
                            :}
                            | op_arithmetical_b:op NUMBER_VALUE:n_val
                            {:
                              NumericValue sym = n_val;
                              if(op.equals("-")){
                                Integer value = - n_val.getValue().intValue();
                                sym = new NumericValue(value);
                              }

                              RESULT = sym;
                            :};

ARITHMETICAL_VALUE         ::= NUMBER_VALUE:n_val
                          {:
                            try{
                              Integer value = n_val.getValue();

                              Type type_number = symbolsTable.get("number");

                              String var_id = backTables.addTempVar(type_number.getSize(),  type_number.getTipoSubyacente());

                              c3a_g.generateC3aInstr(
                                Code.copy,
                                Integer.toString(value),
                                null,
                                var_id
                              );

                              RESULT = new ArithmeticValue(var_id, value);
                            }catch(SymTabError e){
                              throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                            }
                          :}
                          | ID_VALUE:id_val
                          {:
                            try{
                              Tipo main_var_type = id_val.getTipo();

                              if(main_var_type != Tipo.darg && main_var_type != Tipo.dconst && main_var_type != Tipo.dvar){
                                String from = id_valxleft.getLine() + ":" + id_valxleft.getColumn();
                                String to = id_valxright.getLine() + ":" + id_valxright.getColumn();
                                String message = "Invalid arithmetic value type" + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }

                              Type var_dtype = symbolsTable.get(id_val.getTypeName());

                              if(var_dtype.getTipoSubyacente() != TipoSubyacente.TS_NUMBER){
                                String from = id_valxleft.getLine() + ":" + id_valxleft.getColumn();
                                String to = id_valxright.getLine() + ":" + id_valxright.getColumn();
                                String message = "ARITHMETICAL_VALUE: Invalid subjacent type" + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }

                              ArithmeticValue sym;
                              String var_id = id_val.getId();

                              if(main_var_type == Tipo.dconst){
                                Integer value = (Integer) id_val.getValue();
                                sym = new ArithmeticValue(var_id, value);
                              }else{
                                sym = new ArithmeticValue(var_id);
                              }

                              RESULT = sym;
                            }catch(SymTabError e){
                              throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                            }
                          :}
                          | ARITHMETICAL_OPERATION:arith_op
                          {:
                            ArithmeticValue sym;
                            if(arith_op.getIsConst()){
                              sym = new ArithmeticValue(arith_op.getVarId(), arith_op.getValue());
                            }else{
                              sym = new ArithmeticValue(arith_op.getVarId());
                            }

                            RESULT = sym;
                          :}
                          | CALL_FUNCTION:call_fn
                          {:
                            try{
                              Type fn_type = symbolsTable.get(call_fn.getFunctionId());
                              Type dfn_type = symbolsTable.get(fn_type.getTypeName());

                              if(dfn_type.getTipoSubyacente() != TipoSubyacente.TS_NUMBER){
                                String from = call_fnxleft.getLine() + ":" + call_fnxleft.getColumn();
                                String to = call_fnxright.getLine() + ":" + call_fnxright.getColumn();
                                String message = "Invalid function call "+call_fn.getFunctionId() + " with return type "+ dfn_type.getTipoSubyacente() +". Expected :"+TipoSubyacente.TS_NUMBER + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }

                              String var_id = backTables.addTempVar(dfn_type.getSize(), dfn_type.getTipoSubyacente());

                              c3a_g.generateC3aInstr(
                                Code.copy,
                                "return",
                                call_fn.getBackendId(),
                                var_id
                              );

                              RESULT = new ArithmeticValue(var_id);
                            }catch(SymTabError e){
                              String from = call_fnxleft.getLine() + ":" + call_fnxleft.getColumn();
                              String to = call_fnxright.getLine() + ":" + call_fnxright.getColumn();
                              String message = e.getMessage() + " from "+from+" to "+to;
                              throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                            }
                          :}
                          | op_arithmetical_b:op CALL_FUNCTION:call_fn
                          {:
                            try{
                              Type fn_type = symbolsTable.get(call_fn.getFunctionId());
                              Type dfn_type = symbolsTable.get(fn_type.getTypeName());

                              if(dfn_type.getTipoSubyacente() != TipoSubyacente.TS_NUMBER){
                                String from = call_fnxleft.getLine() + ":" + call_fnxleft.getColumn();
                                String to = call_fnxright.getLine() + ":" + call_fnxright.getColumn();
                                String message = "Invalid function call "+call_fn.getFunctionId() + " with return type "+ dfn_type.getTipoSubyacente() +". Expected :"+TipoSubyacente.TS_NUMBER + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }

                              String var_id = backTables.addTempVar(dfn_type.getSize(), dfn_type.getTipoSubyacente());

                              c3a_g.generateC3aInstr(
                                Code.copy,
                                "return",
                                call_fn.getBackendId(),
                                var_id
                              );

                              if(op.equals("-")){
                                c3a_g.generateC3aInstr(
                                  Code.neg,
                                  var_id,
                                  null,
                                  var_id
                                );
                              }

                              RESULT = new ArithmeticValue(var_id);
                            }catch(SymTabError e){
                              String from = call_fnxleft.getLine() + ":" + call_fnxleft.getColumn();
                              String to = call_fnxright.getLine() + ":" + call_fnxright.getColumn();
                              String message = e.getMessage() + " from "+from+" to "+to;
                              throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                            }
                          :};

ID_VALUE                    ::= id:id_val
                            {:
                              try{
                                Type id_type = symbolsTable.get(id_val);
                                String var_id = id_type.getBackendId();
                                Identifier sym = new Identifier(var_id, id_type.getTipo(), id_type.getTypeName());
                                if(id_type.getTipo() == Tipo.dconst){
                                  sym = new Identifier(var_id, id_type.getTipo(), id_type.getTypeName(), id_type.getValue());
                                }

                                RESULT = sym;
                              }catch(SymTabError e){
                                String from = id_valxleft.getLine() + ":" + id_valxleft.getColumn();
                                String to = id_valxright.getLine() + ":" + id_valxright.getColumn();
                                String message = e.getMessage() + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | lparen ID_VALUE:id_val rparen
                            {:
                              RESULT = id_val;
                            :}
                            | op_logical_not:op ID_VALUE:id_val
                            {:
                              try{

                                Identifier sym;
                                // check if unary operator is type valid
                                TipoSubyacente subType = symbolsTable.get(id_val.getTypeName()).getTipoSubyacente();

                                if(subType != TipoSubyacente.TS_BOOLEAN) {
                                  String from = opxleft.getLine() + ":" + opxleft.getColumn();
                                  String to = opxright.getLine() + ":" + opxright.getColumn();
                                  String message = "Invalid unary operator " + op + " for type " + subType + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                Type type_boolean = symbolsTable.get("boolean");
                                String var_id = backTables.addTempVar(type_boolean.getSize(),  type_boolean.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.not,
                                  id_val.getId(),
                                  null,
                                  var_id
                                );

                                if(id_val.getTipo() == Tipo.dconst){
                                  Boolean value = !((Boolean) id_val.getValue()).booleanValue();
                                  sym = new Identifier(var_id, id_val.getTipo(), id_val.getTypeName(), value);
                                }else{
                                  sym = new Identifier(var_id, id_val.getTipo(), id_val.getTypeName());
                                }

                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | op_arithmetical_b:op ID_VALUE:id_val
                            {:
                              try {
                                Identifier sym = id_val;
                                // check if unary operator is type valid
                                TipoSubyacente subType = symbolsTable.get(id_val.getTypeName()).getTipoSubyacente();

                                if(subType != TipoSubyacente.TS_BOOLEAN) {
                                  String from = opxleft.getLine() + ":" + opxleft.getColumn();
                                  String to = opxright.getLine() + ":" + opxright.getColumn();
                                  String message = "Invalid unary operator " + op + " for type " + subType + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                if(op.equals("-")){
                                  Type type_number = symbolsTable.get("number");
                                  String var_id = backTables.addTempVar(type_number.getSize(),  type_number.getTipoSubyacente());

                                  c3a_g.generateC3aInstr(
                                    Code.neg,
                                    id_val.getId(),
                                    null,
                                    var_id
                                  );

                                  if(id_val.getTipo() == Tipo.dconst){
                                    Integer value = -((Integer) id_val.getValue()).intValue();
                                    sym = new Identifier(var_id, id_val.getTipo(), id_val.getTypeName(), value);
                                  }else{
                                    sym = new Identifier(var_id, id_val.getTipo(), id_val.getTypeName());
                                  }
                                }

                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :};

STRING_VALUE                ::= string:string_val
                            {:
                              RESULT = new StringValue(string_val);
                            :}
                            | lparen STRING_VALUE:string_val rparen
                            {:
                              RESULT = string_val;
                            :};

VALUE                       ::= ID_VALUE:id_val
                            {:
                              Value sym;

                              String var_id = id_val.getId();

                              if(id_val.getTipo() == Tipo.dconst){
                                sym = new Value(var_id, id_val.getTipo(), id_val.getTypeName(), id_val.getValue());
                              }
                              else {
                                sym = new Value(var_id, id_val.getTipo(), id_val.getTypeName());
                              }

                              RESULT = sym;
                            :}
                            | STRING_VALUE:str_value
                            {:
                              try{
                                String value = str_value.getString().replace("\"", "");
                                Type type_string = symbolsTable.get("string");

                                if (value.length() > 1000){
                                  String from = str_valuexleft.getLine() + ":" + str_valuexleft.getColumn();
                                  String to = str_valuexright.getLine() + ":" + str_valuexright.getColumn();
                                  String message = "String must be shorter than 1000 characters " + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                // string size in bytes
                                int stringSize = value.length() * type_string.getSize();

                                Value sym = new Value(value, stringSize);

                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | BOOLEAN_VALUE:bool_val
                            {:
                              try{
                                Boolean value = bool_val.getValue();
                                Type type_bool = symbolsTable.get("boolean");

                                String var_id = backTables.addTempVar(type_bool.getSize(), type_bool.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.copy,
                                  value.toString(),
                                  null,
                                  var_id
                                );

                                RESULT = new Value(var_id, TipoSubyacente.TS_BOOLEAN, value);
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | NUMBER_VALUE:n_val
                            {:
                              try{
                                Integer value = n_val.getValue();

                                Type type_number = symbolsTable.get("number");

                                String var_id = backTables.addTempVar(type_number.getSize(), type_number.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.copy,
                                  Integer.toString(value),
                                  null,
                                  var_id
                                );

                                RESULT = new Value(var_id, TipoSubyacente.TS_NUMBER, value);
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | VALUE_COMPARISON:comp_val
                            {:
                              Value sym;
                              String id = comp_val.getVarId();

                              if(comp_val.getIsConst()){
                                Boolean value = comp_val.getValue();
                                sym = new Value(id, TipoSubyacente.TS_BOOLEAN, value);
                              }else{
                                sym = new Value(id, TipoSubyacente.TS_BOOLEAN);
                              }

                              RESULT = sym;
                            :}
                            | op_logical_not VALUE_COMPARISON:comp_val
                            {:
                              try{
                                Value sym;

                                Type type_bool = symbolsTable.get("boolean");
                                String var_id = backTables.addTempVar(type_bool.getSize(), type_bool.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.not,
                                  comp_val.getVarId(),
                                  null,
                                  var_id
                                );

                                if(comp_val.getIsConst()){
                                  Boolean value = ! comp_val.getValue().booleanValue();
                                  sym = new Value(var_id, TipoSubyacente.TS_BOOLEAN, value);
                                }else{
                                  sym = new Value(var_id, TipoSubyacente.TS_BOOLEAN);
                                }

                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | ARITHMETICAL_OPERATION:arith_op
                            {:
                              Value sym;
                              String var_id = arith_op.getVarId();
                              if(arith_op.getIsConst()){
                                sym = new Value(var_id, TipoSubyacente.TS_NUMBER, arith_op.getValue());
                              }else{
                                sym = new Value(var_id, TipoSubyacente.TS_NUMBER);
                              }

                              RESULT = sym;
                            :}
                            | BOOLEAN_OPERATION:bool_op
                            {:
                              Value sym;
                              String var_id = new String(bool_op.getVarId());
                              if(bool_op.getIsConst()){
                                sym = new Value(var_id, TipoSubyacente.TS_BOOLEAN, bool_op.getValue());
                              }else{
                                sym = new Value(var_id, TipoSubyacente.TS_BOOLEAN);
                              }

                              RESULT = sym;
                            :}
                            | CALL_FUNCTION:call_fn
                            {:
                              try{
                                Type fn_type = symbolsTable.get(call_fn.getFunctionId());
                                Type dfn_type = symbolsTable.get(fn_type.getTypeName());

                                if(dfn_type.getTipoSubyacente() == TipoSubyacente.TS_NULL){
                                  String from = call_fnxleft.getLine() + ":" +call_fnxleft.getColumn();
                                  String to = call_fnxright.getLine() + ":" + call_fnxright.getColumn();
                                  String message = "Function call : "+call_fn.getFunctionId() + " does not return any value" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                String var_id = backTables.addTempVar(dfn_type.getSize(), dfn_type.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.copy,
                                  "return",
                                  call_fn.getBackendId(),
                                  var_id
                                );

                                RESULT = new Value(var_id, Tipo.dfun, fn_type.getTypeName());
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | READ lparen rparen
                            {:
                              try{
                                Type number_type = symbolsTable.get("number");
                                String var_id = backTables.addTempVar(number_type.getSize(), number_type.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.read,
                                  null,
                                  null,
                                  var_id
                                );

                                RESULT = new Value(var_id, number_type.getTipoSubyacente());
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | TUPLE_ACCESS
                            {:

                            :}
                            ;

TUPLE_VALUE                 ::= lbracket TUPLE_VALUES:tuple_values rbracket
                            {:
                            RESULT = tuple_values;
                            :}
                            ;

TUPLE_VALUES                ::=  TUPLE_VALUES:values comma VALUE:value
                            {:
                            values.addValue(value);
                            RESULT = values;
                            :}
                            |   VALUE:value
                            {:
                            RESULT = new TupleValues(new ArrayList<>(List.of(value)));
                            :}
                            ;



BOOLEAN_OPERATION           ::= BOOLEAN_OP_VALUE:bool_val1 op_logical:op BOOLEAN_OP_VALUE:bool_val2
                            {:
                              try{
                                BooleanOperator sym;
                                Code op_code;

                                switch(op){
                                  case "&&":
                                    op_code = Code.and;
                                    break;
                                  case "||":
                                    op_code = Code.or;
                                    break;
                                  default :
                                    String from = opxleft.getLine() + ":" + opxleft.getColumn();
                                    String to = opxright.getLine() + ":" + opxright.getColumn();
                                    String message = "Invalid boolean operator" + " from "+from+" to "+to;
                                    throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                boolean allConst = bool_val1.getIsConst() && bool_val2.getIsConst();
                                Boolean value = null;

                                if(allConst){
                                  Boolean val1 = (Boolean) bool_val1.getValue();
                                  Boolean val2 = (Boolean) bool_val2.getValue();
                                  switch(op){
                                  case "&&":
                                    value = val1 && val2;
                                    break;
                                  case "||":
                                    value = val1 || val2;
                                    break;
                                  }
                                }

                                Type type_bool = symbolsTable.get("boolean");
                                String var_id = backTables.addTempVar(type_bool.getSize(), type_bool.getTipoSubyacente());

                                String val1_id = bool_val1.getVarId();
                                String val2_id = bool_val2.getVarId();
                                c3a_g.generateC3aInstr(
                                  op_code,
                                  val1_id,
                                  val2_id,
                                  var_id
                                );

                                if(allConst){
                                  sym = new BooleanOperator(var_id, value);
                                }else{
                                  sym = new BooleanOperator(var_id);
                                }

                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | lparen BOOLEAN_OPERATION:bool_op rparen
                            {:
                              RESULT = bool_op;
                            :}
                            | op_logical_not lparen BOOLEAN_OPERATION:bool_op rparen
                            {:
                              try{
                                BooleanOperator sym;
                                Type type_boolean = symbolsTable.get("boolean");
                                String var_id = backTables.addTempVar(type_boolean.getSize(),  type_boolean.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.neg,
                                  bool_op.getVarId(),
                                  null,
                                  var_id
                                );

                                if(bool_op.getIsConst()){
                                  Boolean value = ! bool_op.getValue().booleanValue();
                                  sym = new BooleanOperator(bool_op.getVarId(), value);
                                }else{
                                  sym = new BooleanOperator(var_id);
                                }

                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :};

BOOLEAN_OP_VALUE            ::= BOOLEAN_VALUE:bool_val
                            {:
                              try{
                                Boolean value = bool_val.getValue();
                                Type type_boolean = symbolsTable.get("boolean");

                                String var_id = backTables.addTempVar(type_boolean.getSize(),  type_boolean.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.copy,
                                  value.toString(),
                                  null,
                                  var_id
                                );

                                RESULT = new BooleanOperationValue(var_id, value);
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | ID_VALUE:id_val
                            {:
                              try{
                                Tipo main_var_type = id_val.getTipo();
                                if(main_var_type != Tipo.darg && main_var_type != Tipo.dconst && main_var_type != Tipo.dvar){
                                  String from = id_valxleft.getLine() + ":" + id_valxleft.getColumn();
                                  String to = id_valxright.getLine() + ":" + id_valxright.getColumn();
                                  String message = "Invalid arithmetic value type" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                Type var_dtype = symbolsTable.get(id_val.getTypeName());

                                if(var_dtype.getTipoSubyacente() != TipoSubyacente.TS_BOOLEAN){
                                  String from = id_valxleft.getLine() + ":" + id_valxleft.getColumn();
                                  String to = id_valxright.getLine() + ":" + id_valxright.getColumn();
                                  String message = "BOOLEAN_OP_VALUE: Invalid subjacent type" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                BooleanOperationValue sym;
                                String var_id = id_val.getId();

                                if(main_var_type == Tipo.dconst){
                                  Boolean value = (Boolean) id_val.getValue();
                                  sym = new BooleanOperationValue(var_id, value);
                                }else{
                                  sym = new BooleanOperationValue(var_id);
                                }

                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | BOOLEAN_OPERATION:bool_op
                            {:
                              BooleanOperationValue sym;
                              if(bool_op.getIsConst()){
                                sym = new BooleanOperationValue(bool_op.getVarId(), bool_op.getValue());
                              }else{
                                sym = new BooleanOperationValue(bool_op.getVarId());
                              }
                              RESULT = sym;
                            :}
                            | VALUE_COMPARISON:comp_val
                            {:
                              BooleanOperationValue sym;
                              String id = new String(comp_val.getVarId());
                              if(comp_val.getIsConst()){
                                sym = new BooleanOperationValue(id, comp_val.getValue());
                              }else{
                                sym = new BooleanOperationValue(id);
                              }

                              RESULT = sym;
                            :}
                            | op_logical_not VALUE_COMPARISON:comp_val
                            {:
                              try{
                                Type type_bool = symbolsTable.get("boolean");
                                String var_id = backTables.addTempVar(type_bool.getSize(), type_bool.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.not,
                                  comp_val.getVarId(),
                                  null,
                                  var_id
                                );

                                BooleanOperationValue sym;
                                if(comp_val.getIsConst()){
                                  Boolean value = ! comp_val.getValue().booleanValue();
                                  sym = new BooleanOperationValue(var_id, value);
                                }else{
                                  sym = new BooleanOperationValue(var_id);
                                }
                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | CALL_FUNCTION:call_fn
                            {:
                              try{
                                Type fn_type = symbolsTable.get(call_fn.getFunctionId());
                                Type dfn_type = symbolsTable.get(fn_type.getTypeName());

                                if(dfn_type.getTipoSubyacente() != TipoSubyacente.TS_BOOLEAN){
                                  String from = call_fnxleft.getLine() + ":" + call_fnxleft.getColumn();
                                  String to = call_fnxright.getLine() + ":" + call_fnxright.getColumn();
                                  String message = "Invalid function call "+call_fn.getFunctionId() + " with return type "+ dfn_type.getTipoSubyacente() +". Expected :"+TipoSubyacente.TS_BOOLEAN + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                String var_id = backTables.addTempVar(dfn_type.getSize(), dfn_type.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.copy,
                                  "return",
                                  call_fn.getBackendId(),
                                  var_id
                                );

                                RESULT = new BooleanOperationValue(var_id);
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | op_logical_not:op CALL_FUNCTION:call_fn
                            {:
                              try{
                                Type fn_type = symbolsTable.get(call_fn.getFunctionId());
                                Type dfn_type = symbolsTable.get(fn_type.getTypeName());

                                if(dfn_type.getTipoSubyacente() != TipoSubyacente.TS_NUMBER){
                                  String from = call_fnxleft.getLine() + ":" + call_fnxleft.getColumn();
                                  String to = call_fnxright.getLine() + ":" + call_fnxright.getColumn();
                                  String message = "Invalid function call "+call_fn.getFunctionId() + " with return type "+ dfn_type.getTipoSubyacente() +". Expected :"+TipoSubyacente.TS_NUMBER + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                String var_id = backTables.addTempVar(dfn_type.getSize(), dfn_type.getTipoSubyacente());

                                c3a_g.generateC3aInstr(
                                  Code.copy,
                                  "return",
                                  call_fn.getBackendId(),
                                  var_id
                                );

                                c3a_g.generateC3aInstr(
                                  Code.neg,
                                  var_id,
                                  null,
                                  var_id
                                );

                                RESULT = new BooleanOperationValue(var_id);
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            ;

BOOLEAN_VALUE               ::= bool:bool_val
                            {:
                              Boolean value = Boolean.valueOf(bool_val);
                              RESULT = new BooleanValue(value);
                            :}
                            | op_logical_not BOOLEAN_VALUE:bool_val
                            {:
                              Boolean value = ! bool_val.getValue().booleanValue();
                              RESULT = new BooleanValue(value);
                            :}
                            | lparen BOOLEAN_VALUE:bool_val rparen
                            {:
                              RESULT = bool_val;
                            :}
                            ;

VALUE_COMPARISON            ::= lparen VALUE:val1 op_relational:op VALUE:val2 rparen
                            {:
                              try{
                                ValuesComparison sym;

                                Tipo type1 = val1.getTipo();
                                TipoSubyacente subType1;

                                if(val1.getTipo() == Tipo.dnull){
                                  subType1 = val1.getTipoSubyacente();
                                }else{
                                  if(type1 != Tipo.dvar && type1 != Tipo.dconst && type1 != Tipo.darg && type1 != Tipo.dfun) {
                                    String from = val1xleft.getLine() + ":" + val1xleft.getColumn();
                                    String to = val1xright.getLine() + ":" + val1xright.getColumn();
                                    String message = "Value 1 of comparison wrong type" + " from "+from+" to "+to;
                                    throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                  }
                                  Type dtype_type = symbolsTable.get(val1.getTypeName());
                                  subType1 = dtype_type.getTipoSubyacente();
                                }
                                // SAME FOR VALUE2
                                Tipo type2 = val2.getTipo();
                                TipoSubyacente subType2;

                                if(val2.getTipo() == Tipo.dnull){
                                  subType2 = val2.getTipoSubyacente();
                                }else{
                                  if(type2 != Tipo.dvar && type2 != Tipo.dconst && type2 != Tipo.darg && type2 != Tipo.dfun) {
                                    String from = val2xleft.getLine() + ":" + val2xleft.getColumn();
                                    String to = val2xright.getLine() + ":" + val2xright.getColumn();
                                    String message = "Value 2 of comparison wrong type" + " from "+from+" to "+to;
                                    throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                  }
                                  Type dtype_type = symbolsTable.get(val2.getTypeName());
                                  subType2 = dtype_type.getTipoSubyacente();
                                }

                                //Check same subtype
                                if(subType1 != subType2) {
                                  String from = val2xleft.getLine() + ":" + val2xleft.getColumn();
                                  String to = val2xright.getLine() + ":" + val2xright.getColumn();
                                  String message = "Value 1 subtype is different from value 2" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                Code op_code = Code.EQ;
                                switch(op){
                                  case "==":
                                    op_code = Code.EQ;
                                    break;
                                  case "!=":
                                    op_code = Code.NE;
                                    break;
                                  case "<":
                                    if(subType1 != TipoSubyacente.TS_NUMBER) {
                                      String from = opxleft.getLine() + ":" + opxleft.getColumn();
                                      String to = opxright.getLine() + ":" + opxright.getColumn();
                                      String message = "This operator ("+op+") only works with integer subtypes" + " from "+from+" to "+to;
                                      throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                    }
                                    op_code = Code.LT;
                                    break;
                                  case "<=":
                                    if(subType1 != TipoSubyacente.TS_NUMBER) {
                                      String from = opxleft.getLine() + ":" + opxleft.getColumn();
                                      String to = opxright.getLine() + ":" + opxright.getColumn();
                                      String message = "This operator ("+op+") only works with integer subtypes" + " from "+from+" to "+to;
                                      throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                    }
                                    op_code = Code.LE;
                                    break;
                                  case ">":
                                    if(subType1 != TipoSubyacente.TS_NUMBER) {
                                      String from = opxleft.getLine() + ":" + opxleft.getColumn();
                                      String to = opxright.getLine() + ":" + opxright.getColumn();
                                      String message = "This operator ("+op+") only works with integer subtypes" + " from "+from+" to "+to;
                                      throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                    }
                                    op_code = Code.GT;
                                    break;
                                  case ">=":
                                    if(subType1 != TipoSubyacente.TS_NUMBER) {
                                      String from = opxleft.getLine() + ":" + opxleft.getColumn();
                                      String to = opxright.getLine() + ":" + opxright.getColumn();
                                      String message = "This operator ("+op+") only works with integer subtypes" + " from "+from+" to "+to;
                                      throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                    }
                                    op_code = Code.GE;
                                    break;
                                }

                                boolean allConst = val1.getIsConst() && val2.getIsConst();

                                Boolean val = null;
                                if(allConst){
                                  switch(op){
                                    case "==":
                                      if(subType1 == TipoSubyacente.TS_NUMBER){
                                        val = (Integer) val1.getValue() == (Integer) val2.getValue();
                                      }
                                      if(subType1 == TipoSubyacente.TS_STRING){
                                        val = ((String)val1.getValue()).equals((String) val2.getValue());
                                      }
                                      if(subType1 == TipoSubyacente.TS_BOOLEAN){
                                        val = (Boolean) val1.getValue() == (Boolean) val2.getValue();
                                      }
                                      break;
                                    case "!=":
                                      if(subType1 == TipoSubyacente.TS_NUMBER){
                                        val = (Integer) val1.getValue() != (Integer) val2.getValue();
                                      }
                                      if(subType1 == TipoSubyacente.TS_STRING){
                                        val = !((String)val1.getValue()).equals((String) val2.getValue());
                                      }
                                      if(subType1 == TipoSubyacente.TS_BOOLEAN){
                                        val = (Boolean) val1.getValue() != (Boolean) val2.getValue();
                                      }
                                      break;

                                    // only integer operators
                                    case "<":
                                      val = (Integer) val1.getValue() < (Integer) val2.getValue();
                                      break;
                                    case "<=":
                                      val = (Integer) val1.getValue() <= (Integer) val2.getValue();
                                      break;
                                    case ">":
                                      val = (Integer) val1.getValue() > (Integer) val2.getValue();
                                      break;
                                    case ">=":
                                      val = (Integer) val1.getValue() >= (Integer) val2.getValue();
                                      break;
                                  }
                                }

                                Type type_bool = symbolsTable.get("boolean");
                                String var_id = backTables.addTempVar(type_bool.getSize(), type_bool.getTipoSubyacente());

                                if(allConst){
                                  sym = new ValuesComparison(var_id, val);
                                }else{
                                  sym = new ValuesComparison(var_id);
                                }

                                c3a_g.generateC3aInstr(
                                  op_code,
                                  val1.getVarId(),
                                  val2.getVarId(),
                                  var_id
                                );

                                RESULT = sym;
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | lparen VALUE_COMPARISON:cmp_val rparen
                            {:
                              RESULT = cmp_val;
                            :};

COND                        ::= BOOLEAN_OP_VALUE:bool_val
                              {:
                                String var_id = bool_val.getVarId();

                                String true_label = backTables.addEtiq();
                                String false_label = backTables.addEtiq();

                                labelTrueStack.push(true_label);
                                labelFalseStack.push(false_label);


                                c3a_g.generateC3aInstr(
                                  Code.jump_cond,
                                  var_id,
                                  "true",
                                  true_label
                                );

                                c3a_g.generateC3aInstr(
                                  Code.go_to,
                                  null,
                                  null,
                                  false_label
                                );

                                RESULT = new Condition();
                              :};

COND_T                      ::=
                              {:
                                String label = labelTrueStack.pop();

                                c3a_g.generateC3aInstr(
                                  Code.skip,
                                  null,
                                  null,
                                  label
                                );

                                RESULT = new CondTrue();
                              :};

COND_F                      ::=
                              {:
                                String label = labelFalseStack.pop();

                                c3a_g.generateC3aInstr(
                                  Code.skip,
                                  null,
                                  null,
                                  label
                                );

                                RESULT = new CondFalse();
                              :};

INSTRUCTION_IF              ::= IF COND lbrace BLOCK_IN COND_T INSTRUCTIONS BLOCK_OUT rbrace INSTRUCT_ELIF INSTRUCT_ELSE
                            {:
                              RESULT = new InstructionIf();
                            :};

M_END                       ::= EMPTY
                            {:
                              String label = backTables.addEtiq();

                              c3a_g.generateC3aInstr(
                                Code.go_to,
                                null,
                                null,
                                label
                              );

                              RESULT = new End(label);
                            :};

INSTRUCT_ELIF                ::= M_END:mend ELIF COND_F COND lbrace BLOCK_IN COND_T INSTRUCTIONS BLOCK_OUT rbrace INSTRUCT_ELIF
                            {:
                              String label = mend.getLabel();

                              c3a_g.generateC3aInstr(
                                Code.skip,
                                null,
                                null,
                                label
                              );

                              RESULT = new ElseIf();
                            :}
                            |
                            {:
                              RESULT = new ElseIf();
                            :};

INSTRUCT_ELSE                        ::= M_END:mend ELSE lbrace BLOCK_IN COND_F INSTRUCTIONS BLOCK_OUT rbrace
                            {:
                              String label = mend.getLabel();

                              c3a_g.generateC3aInstr(
                                Code.skip,
                                null,
                                null,
                                label
                              );

                              RESULT = new Else();
                            :}
                            | COND_F
                            {:
                              RESULT = new Else();
                            :};

M_WHILE                     ::= EMPTY
                            {:
                              String label = backTables.addEtiq();

                              c3a_g.generateC3aInstr(
                                Code.skip,
                                null,
                                null,
                                label
                              );

                              RESULT = new WhileLabel(label);
                            :};

INSTRUCTION_WHILE           ::= WHILE M_WHILE:mwhile COND lbrace BLOCK_IN COND_T INSTRUCTIONS BLOCK_OUT rbrace
                            {:
                              String loop_label = mwhile.getLabel();
                              c3a_g.generateC3aInstr(
                                Code.go_to,
                                null,
                                null,
                                loop_label
                              );

                              String end_label = labelFalseStack.pop();
                              c3a_g.generateC3aInstr(
                                Code.skip,
                                null,
                                null,
                                end_label
                              );

                              RESULT = new InstructionWhile();
                            :};

INSTRUCTION_FOR             ::= FOR lparen FOR_BODY:forBody rparen lbrace BLOCK_IN COND_T INSTRUCTIONS BLOCK_OUT rbrace
                            {:
                              String postInstrLabel = forBody.getLabel();
                              c3a_g.generateC3aInstr(
                                Code.go_to,
                                null,
                                null,
                                postInstrLabel
                              );

                              String end_label = labelFalseStack.pop();
                              c3a_g.generateC3aInstr(
                                Code.skip,
                                null,
                                null,
                                end_label
                              );
                              RESULT = new InstructionFor();
                            :};

LABEL_FOR                   ::= EMPTY
                            {:
                              String label = backTables.addEtiq();

                              c3a_g.generateC3aInstr(
                                Code.skip,
                                null,
                                null,
                                label
                              );

                              RESULT = new ForLabel(label);
                            :};

FOR_BODY                    ::= DECLARATION semicolon LABEL_FOR:labelFor COND semicolon LABEL_POST_FOR:labelPostFor OPERATOR_ASSIG
                                {:
                                    String iniForLabel = labelFor.getLabel();
                                    c3a_g.generateC3aInstr(
                                      Code.go_to,
                                      null,
                                      null,
                                      iniForLabel
                                    );

                                    RESULT = new ForBody(labelPostFor.getLabel());
                                :};

LABEL_POST_FOR              ::= EMPTY
                            {:
                              String label = backTables.addEtiq();

                              c3a_g.generateC3aInstr(
                                Code.skip,
                                null,
                                null,
                                label
                              );

                              RESULT = new LabelPostFor(label);
                            :};

CALL_FUNCTION               ::= id:fun_id lparen:lp rparen:rp
                            {:
                              try{
                                // Check if function and has params
                                int num_params = symbolsTable.getNumParams(fun_id);
                                if(num_params > 0 ){
                                  String from = lpxleft.getLine() + ":" + lpxleft.getColumn();
                                  String to = rpxright.getLine() + ":" + rpxright.getColumn();
                                  String message = "Missing parameters. Function " + fun_id + " has " + num_params + " parameters" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                Type fun_type = symbolsTable.get(fun_id);
                                String backId = fun_type.getBackendId();
                                c3a_g.generateC3aInstr(
                                  Code.call,
                                  0 + "",
                                  null,
                                  backId
                                );

                                RESULT = new CallFunction(fun_id, backId);
                              }catch(SymTabError e){
                                String from = fun_idxleft.getLine() + ":" + fun_idxleft.getColumn();
                                String to = fun_idxright.getLine() + ":" + fun_idxright.getColumn();
                                String message = e.getMessage() + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | CALL_BODY:body rparen:rp
                            {:
                              try{
                                int body_params = body.getNumParams();
                                String fun_id = body.getFunId();
                                int fun_params = symbolsTable.getNumParams(fun_id);

                                if(fun_params != body_params){
                                  String from = bodyxleft.getLine() + ":" + bodyxleft.getColumn();
                                  String to = rpxright.getLine() + ":" + rpxright.getColumn();
                                  String message = "Missing parameters. Function " + fun_id + " has " + fun_params + " parameters" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                String fun_backId = body.getFunBackId();
                                c3a_g.generateC3aInstr(
                                  Code.call,
                                  fun_params + "",
                                  null,
                                  fun_backId
                                );



                                RESULT = new CallFunction(fun_id, fun_backId);
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :};

CALL_BODY                   ::= CALL_BODY:body comma VALUE:value
                            {:
                              try{
                                String fun_id = body.getFunId();
                                int num_params = body.getNumParams();
                                TipoSubyacente subType;

                                if(value.getTipo() == Tipo.dnull){
                                  subType = value.getTipoSubyacente();
                                }
                                else{
                                  if(value.getTipo() != Tipo.dvar && value.getTipo() != Tipo.dconst && value.getTipo() != Tipo.darg){
                                    String from = valuexleft.getLine() + ":" + valuexleft.getColumn();
                                    String to = valuexright.getLine() + ":" + valuexright.getColumn();
                                    String message = fun_id + ". Incorrect type for param "+ num_params + " from "+from+" to "+to;
                                    throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                  }
                                  Type value_type = symbolsTable.get(value.getTypeName());
                                  subType = value_type.getTipoSubyacente();
                                }

                                //Check param type with function param type
                                Type paramType = symbolsTable.getParam(fun_id, num_params);
                                TipoSubyacente paramSubType = symbolsTable.get(paramType.getTypeName()).getTipoSubyacente();

                                if (paramSubType != subType){
                                  String from = valuexleft.getLine() + ":" + valuexleft.getColumn();
                                  String to = valuexright.getLine() + ":" + valuexright.getColumn();
                                  String message = fun_id + ". Incorrect type for param " + num_params + ". Expected " + subType + " but got " + paramSubType + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                String fun_back_id = body.getFunBackId();
                                c3a_g.generateC3aInstr(
                                  Code.param,
                                  value.getVarId(),
                                  null,
                                  fun_back_id
                                );

                                RESULT = new CallBody(fun_id, fun_back_id, num_params+1);
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | id:fun_id lparen VALUE:value
                            {:
                              try{
                                TipoSubyacente subType;

                                if(value.getTipo() == Tipo.dnull){
                                  subType = value.getTipoSubyacente();
                                }
                                else{
                                  if(value.getTipo() != Tipo.dvar && value.getTipo() != Tipo.dconst && value.getTipo() != Tipo.darg){
                                    String from = valuexleft.getLine() + ":" + valuexleft.getColumn();
                                    String to = valuexright.getLine() + ":" + valuexright.getColumn();
                                    String message = fun_id + ". Incorrect type for param 0" + " from "+from+" to "+to;
                                    throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                  }
                                  Type value_type = symbolsTable.get(value.getTypeName());
                                  subType = value_type.getTipoSubyacente();
                                }

                                //Check param type with function param type
                                Type paramType = symbolsTable.getParam(fun_id, 0);
                                TipoSubyacente paramSubType = symbolsTable.get(paramType.getTypeName()).getTipoSubyacente();

                                if(paramSubType != subType){
                                  String from = valuexleft.getLine() + ":" + valuexleft.getColumn();
                                  String to = valuexright.getLine() + ":" + valuexright.getColumn();
                                  String message = fun_id + ". Incorrect type for param 0. Expected " + subType + " but got " + paramSubType + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                Type fun_type = symbolsTable.get(fun_id);
                                String fun_back_id = fun_type.getBackendId();

                                c3a_g.generateC3aInstr(
                                  Code.param,
                                  value.getVarId(),
                                  null,
                                  fun_back_id
                                );

                                RESULT = new CallBody(fun_id, fun_back_id, 0+1);
                              }catch(SymTabError e){
                                String from = fun_idxleft.getLine() + ":" + fun_idxleft.getColumn();
                                String to = fun_idxright.getLine() + ":" + fun_idxright.getColumn();
                                String message = e.getMessage() + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }
                            :};

INSTRUCTION_OUT             ::= PRINT lparen VALUE:value rparen
                            {:
                              try{
                                String var_id = value.getVarId();
                                TipoSubyacente subtype;

                                if(value.getTipo() == Tipo.dnull){
                                  subtype = value.getTipoSubyacente();
                                }else{
                                  Type var_type = symbolsTable.get(value.getTypeName());
                                  subtype = var_type.getTipoSubyacente();
                                }

                                if (value.getTipo() == Tipo.dnull && value.getTipoSubyacente() == TipoSubyacente.TS_STRING) {
                                  var_id = backTables.addTemporalStringVariable(value.getStringSize(), (String) value.getValue());
                                  c3a_g.generateC3aInstr(
                                    Code.print,
                                    subtype.toString(),
                                    (String) value.getValue(),
                                    var_id
                                  );
                                } else {
                                  c3a_g.generateC3aInstr(
                                    Code.print,
                                    subtype.toString(),
                                    null,
                                    var_id
                                  );
                                }
                                RESULT = new InstructionOut();
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :};

DEFINE_FUNCTION             ::= FUNCTION_INIT:fun_init lbrace BLOCK_IN FUNCTION_INSTRUCTIONS FUNCTION_RETURN:fun_ret BLOCK_OUT rbrace
                            {:
                              //check if fun type and return type are the same
                              if(fun_init.getTipoSubyacente() != fun_ret.getTipoSubyacente()) {
                                String from = fun_retxleft.getLine() + ":" + fun_retxleft.getColumn();
                                String to = fun_retxright.getLine() + ":" + fun_retxright.getColumn();
                                String message = "Invalid return type. Expected : "+fun_init.getTipoSubyacente()+", but got: "+fun_ret.getTipoSubyacente() + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }

                              // no return value
                              if(fun_init.getTipoSubyacente() == TipoSubyacente.TS_NULL){
                                c3a_g.generateC3aInstr(
                                  Code.rtn,
                                  null,
                                  null,
                                  fun_init.getFunId()
                                );
                              }
                              // return value
                              else{

                                c3a_g.generateC3aInstr(
                                  Code.rtn,
                                  fun_ret.getVarId(),
                                  null,
                                  fun_init.getFunId()
                                );
                              }

                              RESULT = new DefineFunction();
                            :};

FUNCTION_INIT               ::= FUNC id:fun_id FUNCTION_PARAMS:fun_params rparen two_points id:type_id
                            {:
                              try{
                                // check return type
                                Type return_fun_type = symbolsTable.get(type_id);
                                if(return_fun_type.getTipo() != Tipo.dtype){
                                  String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                  String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                  String message = "Function declaration : invalid type" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }
                                if(return_fun_type.getTipoSubyacente() == TipoSubyacente.TS_STRING){
                                  String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                  String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                  String message = "Invalid return type : "+type_id+". Valid return types are : boolean or number" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                TipoSubyacente subType = return_fun_type.getTipoSubyacente();
                                ArrayList<Parameter> params = fun_params.getParams();
                                String backId = backTables.addProcedure(fun_id, params.size(), 0, subType);

                                Type fun_type = new Type(backId, Tipo.dfun, type_id);

                                symbolsTable.add(fun_id, fun_type);

                                // add params if it has
                                for(Parameter param : params){
                                  Type param_type = param.getType();
                                  TipoSubyacente param_subType = symbolsTable.get(param.getType().getTypeName()).getTipoSubyacente();
                                  String param_backId = backTables.addVariable(param.getVarId(), param_subType, param.getSize(), true);
                                  param_type.setIdBack(param_backId);
                                  symbolsTable.addParam(fun_id, param_backId, param.getVarId(), param_type);
                                }

                                c3a_g.generateC3aInstr(
                                  Code.skip,
                                  null,
                                  null,
                                  backId
                                );

                                c3a_g.generateC3aInstr(
                                  Code.pmb,
                                  null,
                                  null,
                                  backId
                                );

                                RESULT = new FunctionInit(backId, subType);
                              }catch(SymTabError e){
                                String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                String message = e.getMessage() + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }
                            :};

FUNCTION_PARAMS             ::= FUNCTION_W_PARAMS:params
                            {:
                              RESULT = new FunctionParams(params.getParams());
                            :}
                            | lparen
                            {:
                              RESULT = new FunctionParams();
                            :};

FUNCTION_W_PARAMS           ::= FUNCTION_W_PARAMS:prev_params comma id:id two_points id:type_id
                            {:
                              try{
                                //check param type
                                Type type_type = symbolsTable.get(type_id);
                                if(type_type.getTipo() != Tipo.dtype){
                                  String from = idxleft.getLine() + ":" + idxleft.getColumn();
                                  String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                  String message = "Invalid param type" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }
                                if(type_type.getTipoSubyacente() == TipoSubyacente.TS_STRING){
                                  String from = idxleft.getLine() + ":" + idxleft.getColumn();
                                  String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                  String message = "Invalid param type : "+type_id+". Valid params types are : boolean or number" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                Type param_type = new Type(Tipo.darg, type_id);

                                Parameter param = new Parameter(id, param_type, type_type.getSize());

                                RESULT = new FunctionWithParams(param, prev_params);
                              }catch(SymTabError e){
                                String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                String message = e.getMessage() + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | lparen id:id two_points id:type_id
                            {:
                              try{
                                //check param type
                                Type type_type = symbolsTable.get(type_id);
                                if(type_type.getTipo() != Tipo.dtype){
                                  String from = idxleft.getLine() + ":" + idxleft.getColumn();
                                  String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                  String message = "Invalid param type" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }
                                if(type_type.getTipoSubyacente() == TipoSubyacente.TS_STRING){
                                  String from = idxleft.getLine() + ":" + idxleft.getColumn();
                                  String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                  String message = "Invalid param type : "+type_id+". Valid params types are : boolean or number" + " from "+from+" to "+to;
                                  throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                                }

                                Type param_type = new Type(Tipo.darg, type_id);

                                Parameter param = new Parameter(id, param_type, type_type.getSize());

                                RESULT = new FunctionWithParams(param);
                              }catch(SymTabError e){
                                String from = type_idxleft.getLine() + ":" + type_idxleft.getColumn();
                                String to = type_idxright.getLine() + ":" + type_idxright.getColumn();
                                String message = e.getMessage() + " from "+from+" to "+to;
                                throw new CompilerError(message, CompilerError.ErrorType.SEMANTIC);
                              }
                            :};

FUNCTION_INSTRUCTIONS       ::= INSTRUCTIONS
                            {:
                              RESULT = new FunctionInstructions();
                            :}
                            |
                            {:
                              RESULT = new FunctionInstructions();
                            :};

FUNCTION_RETURN             ::= RETURN VALUE:value semicolon
                            {:
                              try{
                                // is literall
                                TipoSubyacente subType = null;
                                if(value.getTipo() == Tipo.dnull){
                                  subType = value.getTipoSubyacente();
                                }

                                // is variable
                                if(value.getTipo() != Tipo.dnull){
                                  Type type_type = symbolsTable.get(value.getTypeName());
                                  subType = type_type.getTipoSubyacente();
                                }

                                RESULT = new FunctionReturn(value.getVarId(), subType);
                              }catch(SymTabError e){
                                throw new CompilerError(e.getMessage(), CompilerError.ErrorType.SEMANTIC);
                              }
                            :}
                            | EMPTY
                            {:
                              RESULT = new FunctionReturn();
                            :};

EMPTY                       ::= {: RESULT = new Empty(); :};